### ISSUE TITLE
API vs. UI

### ISSUE THREAD

**Issue by ema-rose** [nesya04061919/wordnik-repl#3]
Identify the differences between API and UI on Wordnik.

**Comment by recursivelycurious** [comment]
As covered in our last hack session, the ability to use the wordnik api test interface accomplishes this for us. We have a simple interface to test calls and see data returned to determine what data/objects we actually have available from the API to drive behavior in our game.

That is, we can take a question of the form "would the game be able to do X" and transform it as follows:

In order to do X, the game would have to (for example):
- know what lists a user has
- know what words are on those lists
- remove a word from list A
- add a word to list B

And each of these items above are things that we can directly test against the wordnik api before writing any code.
